(() => {
  const clone=o=>JSON.parse(JSON.stringify(o));
  let data=clone(window.PORTFOLIO_DATA); try{const s=localStorage.getItem('ms_portfolio_data');if(s)data=JSON.parse(s)}catch(e){}
  const sections=['profile','experience','community','education','publications','projects','teaching','certifications','skills','websites','customSections','raw'];
  const names={profile:'Profile',experience:'Experience',community:'Activities',education:'Education',publications:'Publications',projects:'Projects',teaching:'Teaching',certifications:'Certifications',skills:'Skills',websites:'Websites',customSections:'Additional sections',raw:'Advanced JSON'};
  let current='profile';
  const q=s=>document.querySelector(s), esc=(s='')=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  function toast(m){const d=document.createElement('div');d.className='toast';d.textContent=m;document.body.appendChild(d);setTimeout(()=>d.remove(),1700)}
  function save(){localStorage.setItem('ms_portfolio_data',JSON.stringify(data));toast('Saved locally')}
  function menu(){q('#sectionMenu').innerHTML=sections.map(s=>`<button class="menu-btn ${s===current?'active':''}" data-s="${s}">${names[s]}</button>`).join('');document.querySelectorAll('.menu-btn').forEach(b=>b.onclick=()=>{current=b.dataset.s;render()})}
  const langField=(obj,key,label)=>`<div class="field"><label>${label} · EL</label><textarea data-path="${key}.el">${esc(obj?.[key]?.el||'')}</textarea></div><div class="field"><label>${label} · EN</label><textarea data-path="${key}.en">${esc(obj?.[key]?.en||'')}</textarea></div>`;
  const simple=(key,val,label,area=false)=>`<div class="field"><label>${label}</label>${area?`<textarea data-path="${key}">${esc(val||'')}</textarea>`:`<input data-path="${key}" value="${esc(val||'')}">`}</div>`;
  function bindObject(container,obj){container.querySelectorAll('[data-path]').forEach(el=>el.oninput=()=>{const parts=el.dataset.path.split('.');let t=obj;while(parts.length>1){const p=parts.shift();t[p]=t[p]||{};t=t[p]}t[parts[0]]=el.value;save()})}
  function profile(){const p=data.profile;q('#editor').innerHTML=`<div class="edit-card"><h3>Public profile</h3><div class="editor-grid">${simple('name',p.name,'Name')}${simple('email',p.email,'Email')}${simple('linkedin',p.linkedin,'LinkedIn')}${langField(p,'role','Role')}${langField(p,'availability','Eyebrow')}${langField(p,'location','Location')}${langField(p,'about','About')}</div><p class="note">Phone is intentionally not part of the public profile.</p></div>`;bindObject(q('#editor'),p)}
  function arrayEditor(){const arr=data[current]||[];q('#editor').innerHTML=`<div class="editor-grid">${arr.map((it,i)=>itemForm(it,i)).join('')}</div>`;q('#editor').querySelectorAll('.edit-card').forEach((card,i)=>{if(current==='skills'){const inp=card.querySelector('[data-skill]'); if(inp) inp.oninput=()=>{arr[i]=inp.value;save()}} else {bindObject(card,arr[i])} card.querySelector('[data-del]').onclick=()=>{arr.splice(i,1);save();renderEditor()}})}
  function itemForm(it,i){if(current==='skills')return `<div class="edit-card"><h3>Skill ${i+1}</h3><div class="field"><label>Skill</label><input data-skill value="${esc(it)}"></div><div class="item-actions"><button class="small-btn" data-del>Delete</button></div></div>`;
    if(current==='publications')return `<div class="edit-card"><h3>Publication ${i+1}</h3>${simple('title',it.title,'Title',true)}${simple('venue',it.venue,'Venue / year')}<div class="item-actions"><button class="small-btn" data-del>Delete</button></div></div>`;
    if(current==='websites')return `<div class="edit-card"><h3>Website ${i+1}</h3>${simple('name',it.name,'Name')}${simple('url',it.url,'URL')}<div class="item-actions"><button class="small-btn" data-del>Delete</button></div></div>`;
    return `<div class="edit-card"><h3>Item ${i+1}</h3>${langField(it,'title','Title')}${simple('org',it.org||it.issuer||'','Organization / issuer')}${langField(it,'period','Period')}${langField(it,'description','Description')}<div class="field"><label>Tags (comma separated)</label><input data-tags value="${esc((it.tags||[]).join(', '))}"></div><div class="field"><label>Bullets EL (one per line)</label><textarea data-bullets="el">${esc((it.bullets?.el||[]).join('\n'))}</textarea></div><div class="field"><label>Bullets EN (one per line)</label><textarea data-bullets="en">${esc((it.bullets?.en||[]).join('\n'))}</textarea></div><div class="item-actions"><button class="small-btn" data-del>Delete</button></div></div>`}
  function renderEditor(){q('#editorTitle').textContent=names[current];q('#addBtn').style.display=['profile','raw'].includes(current)?'none':'inline-flex';if(current==='profile')profile();else if(current==='raw'){q('#editor').innerHTML=`<textarea id="rawBox" class="json-box">${esc(JSON.stringify(data,null,2))}</textarea><div class="item-actions"><button id="applyRaw" class="primary-btn">Apply JSON</button></div>`;q('#applyRaw').onclick=()=>{try{data=JSON.parse(q('#rawBox').value);save();render()}catch(e){alert('Invalid JSON: '+e.message)}}}else if(current==='customSections'){q('#editor').innerHTML='<div class="edit-card"><h3>Additional sections</h3><p>Για το prototype, οι custom sections διαχειρίζονται από το Advanced JSON. Η βασική δομή είναι <code>{title:{el,en}, intro:{el,en}, items:[]}</code>.</p></div>';q('#addBtn').onclick=()=>{data.customSections=data.customSections||[];data.customSections.push({title:{el:'Νέα ενότητα',en:'New section'},intro:{el:'',en:''},items:[]});save();current='raw';render()}}else arrayEditor();
    if(!['profile','raw','customSections'].includes(current)){q('#editor').querySelectorAll('[data-tags]').forEach((el,i)=>el.oninput=()=>{data[current][i].tags=el.value.split(',').map(x=>x.trim()).filter(Boolean);save()});q('#editor').querySelectorAll('[data-bullets]').forEach((el)=>el.oninput=()=>{const card=[...q('#editor').querySelectorAll('.edit-card')].indexOf(el.closest('.edit-card'));data[current][card].bullets=data[current][card].bullets||{};data[current][card].bullets[el.dataset.bullets]=el.value.split('\n').map(x=>x.trim()).filter(Boolean);save()})}
  }
  function add(){if(current==='skills')data.skills.push('New skill');else if(current==='publications')data.publications.push({title:'New publication',venue:''});else if(current==='websites')data.websites.push({name:'New website',url:'https://'});else if(Array.isArray(data[current]))data[current].push({title:{el:'Νέο στοιχείο',en:'New item'},org:'',period:{el:'',en:''},description:{el:'',en:''},bullets:{el:[],en:[]},tags:[]});save();renderEditor()}
  function render(){menu();renderEditor();q('#addBtn').onclick=add}
  q('#saveBtn').onclick=save;q('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='portfolio-data.json';a.click();URL.revokeObjectURL(a.href)};
  q('#importFile').onchange=async e=>{try{data=JSON.parse(await e.target.files[0].text());save();render()}catch(err){alert('Invalid JSON file')}};
  q('#resetBtn').onclick=()=>{if(confirm('Reset all local changes?')){localStorage.removeItem('ms_portfolio_data');data=clone(window.PORTFOLIO_DATA);render();toast('Reset complete')}};
  render();
})();
